export const projects = [
  {
    title: 'BlackJack',
    folder: 'blackJack',
    genre: 'game',
    urlLive: 'https://onchetrit.github.io/blackjack/',
    urlGithub: 'https://github.com/OnChetrit/blackjack',
    thumbnails: [1, 2, 3, 4, 5],
    desc: [
      'Play Blackjack with my React.js game.',
      'Bet, hit, and stand your way to 21.',
      'Styled with Sass for a sleek and responsive design.',
    ],
    madeWith: ['reactjs', 'javascript', 'sass'],
  },
  {
    title: 'Looper App',
    folder: 'looper',
    genre: 'audio',
    urlLive: 'https://onchetrit.github.io/looper-app/',
    urlGithub: 'https://github.com/OnChetrit/looper-app',
    thumbnails: [1],
    desc: [
      'This project use Web Audio API & Canvas API,',
      'this app allows you to play with the audio files',
      'I use web audio api so that I can play audio loops without gaps',
      'adjust volume and make audio inActive',
    ],
    madeWith: ['reactjs', 'javascript', 'sass'],
  },
  // {
  //   title: "Wednesday",
  //   folder: "wednesday",
  //   genre: "project management platform",
  //   urlLive: "http://wednesday-app.herokuapp.com/",
  //   urlGithub: "https://github.com/ronbuchris/wednesday",
  //   thumbnails: [1, 2, 3, 4, 5],
  //   desc: [
  //     '"Monday" clone, single page End-to-End application.',
  //     'built over a span of two weeks and is based on the "Monday" platform.',
  //     "allows real-time task management using WebSockets.",
  //     "Easily build, run, and scale your dream workflows on one platform",
  //     "adjust to shifting needs, create transparency, connect collaboratively, and stop doing manual grunt work.",
  //   ],
  //   madeWith: ["reactjs", "javascript", "sass", "nodejs", "mongodb"],
  // },
  {
    title: 'AppSus',
    folder: 'appsus',
    genre: 'Multi-App',
    urlLive: 'https://onchetrit.github.io/AppSusSprint3/#/',
    urlGithub: 'https://github.com/OnChetrit/AppSusSprint3',
    thumbnails: [1, 2, 3, 4, 5],
    desc: [
      'my first project with React.js, 3 apps in one place!',
      '"Gmail" clone - send, recieve and delete local emails, save in different catagories',
      '"Keep" clone - create notes with ease, costumize by color, pin your favorite notes.',
      'Book shop - post reviews of books with book API',
    ],
    madeWith: ['javascript', 'reactjs', 'css'],
  },
  {
    title: 'Meme Generator',
    folder: 'meme-gen',
    genre: 'creative',
    urlLive: 'https://onchetrit.github.io/on-chetrit-meme-generator/',
    urlGithub: 'https://github.com/OnChetrit/on-chetrit-meme-generator',
    thumbnails: [1, 2],
    desc: [
      'Project created with canvas',
      'Easily add captions to photos, Use your own images or access a large collection of memes.',
      'Save your meme or export to your device.',
    ],
    madeWith: ['javascript', 'html', 'css'],
  },
  {
    title: 'Touch the numbers',
    folder: 'touch-nums',
    genre: 'game',
    urlLive: 'https://onchetrit.github.io/TouchNums/',
    urlGithub: 'https://github.com/OnChetrit/TouchNums',
    thumbnails: [1],
    desc: [
      'Beat the time!',
      'Click on the numbers in ascending order according to the level and do it in the best time.',
    ],
    madeWith: ['javascript', 'html', 'css'],
  },
  {
    title: 'Minesweeper',
    folder: 'minesweeper',
    genre: 'game',
    urlLive: 'https://onchetrit.github.io/MineSweeperOnChetrit/',
    urlGithub: 'https://github.com/OnChetrit/MineSweeperOnChetrit',
    thumbnails: [1, 2, 3, 4],
    desc: [
      'Play the classic game in multiple difficulties.',
      'How to play ? ',
      'Uncover the number board without detonating bombs',
      'Each number represents the amount of bombs his neighbors circle',
      'Features: 3 LIVES, 3 Hints that help you to find bombs',
      'Left click - cell opening.',
      'Right click - Flag / Unflag.',
      'Wheel click - Opens the surrounding cells only if the number of surrounding bombs is marked as the number on the pressed cell.',
    ],
    madeWith: ['javascript', 'html', 'css'],
  },
];
